

services:
  # Etapa 1: MySQL
  db:
    build:
      context: ./database
    container_name: jogosueca_db
    restart: always
    environment:
      MYSQL_DATABASE: jogosueca
      MYSQL_USER: sueca_user
      MYSQL_PASSWORD: sueca_password
      MYSQL_ROOT_PASSWORD: sueca_root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - sueca_network

  # Etapa 2 e 4: Portal PHP
  www:
    build: 
      context: ./www
      dockerfile: Dockerfile
    container_name: jogosueca_portal
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db
    networks:
      - sueca_network

  # Etapa 3 e 4: API Laravel
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    container_name: jogosueca_api
    restart: always
    ports:
      - "8001:80"
    volumes:
      - ./api:/var/www/html
    depends_on:
      - db
    networks:
      - sueca_network
    
  

networks:
  sueca_network:
    driver: bridge

volumes:
  db_data: